defaults:
  - _self_
  - data: dnabert                # Update to DNABERT-specific datamodule
  - model: dnabert               # Update to DNABERT-specific model
  - callbacks: default
  - logger: mlflow     
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
  - experiment: null
  - hparams_search: null
  - optional local: default
  - debug: null

model:
  _target_: src.models.dnabert_module.DNABERTModule
  model_name_or_path: zhihan1996/DNABERT-2-117M
  learning_rate: 3e-5
  num_labels: 2

task_name: "train_dnabert2"

tags: ["dnabert2", "baseline"]

train: true
test: true

ckpt_path: null                   # Set a checkpoint path if resuming training
seed: 42                          # Set a seed for reproducibility
